---
#
# Default configuration for the current switch
#

#
# Spine / Leaf uplink parameters
#

# Number of port of the switch
number_of_ports:
  "{{ ansible_facts['interfaces'] | select('match', 'swp*') | length }}"

# Switchport number start for the connection from spine to leaf
spine_leaf_swp_start: 1

# Switchport number start for the peerlink
mlag_peerlink_swp_start: "{{ number_of_ports | int - 1 }}"
