---
#
# Configuration for the Mellanox SN2010
#

# Ports speed
# 8x  25 Gbps (swp1-18)
# 4x 100 Gbps (swp19-22)

#
# Spine / Leaf uplink parameters
#

# Number of port of the switch
number_of_ports:
  "{{ ansible_facts['interfaces'] | select('match', 'swp*') | length }}"

# Switchport number start for the connection from spine to leaf
# Using the first 100 Gbps port
spine_leaf_swp_start: 19

# Switchport number start for the peerlink
# Using the last two 25 Gbps ports
mlag_peerlink_swp_start: 17
