---
# tasks file for spine-leaf

#
# Include vars for the current site
#
- name: Include vars for the current switch
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "site_{{ site }}.yml"
        - "site_default.yml"

#
# Setting facts for Spines and Leafs
#
- name: Setting facts for Spine
  vars:
    node_id:
      "{{ groups['spine'] |
      ansible.utils.index_of('eq', inventory_hostname) + 1 }}"
  set_fact:
    hostname: 'SP-{{ site }}{{ "%02d" | format(node_id | int) }}'
    loopback: "{{ loopback_prefix }}.{{ site_id }}.{{ node_id }}"
    asn: '{{ asn_prefix }}{{ site_id }}{{ "%02d" | format(asn_spine_id) }}'
  when: "'spine' in group_names"

- name: Setting facts for Leafs
  vars:
    node_id:
      "{{ groups['leaf'] |
      ansible.utils.index_of('eq', inventory_hostname) + 1 }}"
  set_fact:
    hostname: 'LF-{{ site }}{{ "%02d" | format(node_id | int) }}'
    loopback: "{{ loopback_prefix }}.{{ site_id }}.{{ (node_id | int) + 20 }}"
    asn:
      '{{ asn_prefix }}{{ site_id }}{{ "%02d" | format(node_id | int + 20) }}'
  when: "'leaf' in group_names"

- name: Setting facts for mLag
  set_fact:
    mlag_mac: '{{ mlag_mac_prefix }}:{{ "%02d" | format(site_id) }}:{{ "%02d" |
      format(mlag_shared_id) }}'
    mlag_ip_backup:
      '{{ loopback_prefix }}.{{ site_id }}.{{ mlag_pair_id + 20 }}'
    mlag_shared_ip:
      '{{ mlag_prefix }}.{{ site_id }}.{{ mlag_shared_id + 20 }}'
  when:
    "'leaf' in group_names and (mlag_pair_id is defined) and (bonds is defined)"


#
# Setting global configuration
#
- name: Setting Hostname
  ansible.builtin.include_tasks: set_global_conf.yml
  register: output

#
# Setting BGP for spines
#
- name: Setting BGP for Spines
  ansible.builtin.include_tasks: set_bgp_spine.yml
  when: "'spine' in group_names"


#
# Setting BGP for leafs
#
- name: Setting BGP for Leafs
  ansible.builtin.include_tasks: set_bgp_leaf.yml
  when: "'leaf' in group_names"

#
# Setting vLANs on the Leafs
#
- name: Setting vLANs for Leafs
  ansible.builtin.include_tasks: set_vlan_leaf.yml
  when: "'leaf' in group_names"

#
# Setting uplink Leafs
#
- name: Setting uplinks
  ansible.builtin.include_tasks: set_uplinks.yml
  when: "'leaf' in group_names and (uplinks is defined)"

#
# Setting mLAG on desired Leafs
#
- name: Setting mLag
  ansible.builtin.include_tasks: set_mlag.yml
  when:
    "'leaf' in group_names and (mlag_pair_id is defined) and (bonds is defined)"

#
#
# Setting Access ports on the Leafs
#
#- name: Setting Access Ports for the Leafs
#  ansible.builtin.include_tasks: set_nv_commands.yml
#  when: "'leaf' in group_names"
#  vars:
#    cmd:
#      - nv set interface swp5-6 bridge domain br_default access 100
