---
# tasks file for spine-leaf

#
# Include vars for the current site
#
- name: Include vars for the current switch
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "site_{{ site }}.yml"
        - "site_default.yml"

#
# Include vars for the current switch model
#
- name: Include vars for the current switch
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "switch_{{ ansible_facts['product_name'] }}.yml"
        - "switch_default.yml"

#
# Setting facts for Spines and Leafs
#
- name: Setting Facts
  ansible.builtin.include_tasks: set_facts.yml
  register: output

#
# Setting global configuration
#
- name: Setting Hostname
  ansible.builtin.include_tasks: set_global_conf.yml
  register: output

#
# Setting BGP for spines
#
- name: Setting BGP for Spines
  ansible.builtin.include_tasks: set_bgp_spine.yml
  when: "'spine' in group_names"


#
# Setting BGP for leafs
#
- name: Setting BGP for Leafs and Borders
  ansible.builtin.include_tasks: set_bgp_leaf.yml
  when: "'leaf' in group_names or 'border' in group_names"

#
# Setting vLANs on the Leafs and Borders
#
- name: Setting vLANs for Leafs and Borders
  ansible.builtin.include_tasks: set_vlans.yml
  when: "'leaf' in group_names or 'border' in group_names"

#
# Setting uplink Leafs and Borders
#
- name: Setting uplinks
  ansible.builtin.include_tasks: set_uplinks.yml
  when: "('leaf' in group_names or 'border' in group_names)
  and (uplinks is defined)"

#
# Setting mLAG on desired Leafs
#
- name: Setting mLag
  ansible.builtin.include_tasks: set_mlag.yml
  when:
    "('leaf' in group_names or 'border' in group_names)
    and (bonds is defined)"

#
#
# Setting Access ports on the Leafs
#
#- name: Setting Access Ports for the Leafs
#  ansible.builtin.include_tasks: set_nv_commands.yml
#  when: "'leaf' in group_names"
#  vars:
#    cmd:
#      - nv set interface swp5-6 bridge domain br_default access 100
