---

#
# Setting mLAG
#
- name: Setting mLag
  ansible.builtin.include_tasks: set_nv_commands.yml
  vars:
    bond_qty: "{{ bonds | split(',') | length }}"
    bond_range: "{{ '1-' + bond_qty if bond_qty | int > 1 else '1' }}"
    cmd:
      - nv set interface bond{{ bond_range }} bridge domain br_default
      - nv set mlag mac-address {{ mlag_mac }}
      - nv set mlag backup {{ mlag_ip_backup }}
      - nv set mlag peer-ip linklocal
      - nv set nve vxlan mlag shared-address {{ mlag_shared_ip }}
      - nv set vrf default router bgp neighbor peerlink.4094 remote-as external
      - nv set vrf default router bgp neighbor peerlink.4094
        address-family l2vpn-evpn enable on
      - nv set mlag init-delay 30

#
# Setting Bonds
#
- name: Settings bonds
  ansible.builtin.include_tasks: set_nv_commands.yml
  vars:
    bond: "{{ bonds_item }}"
    bond_id: "{{ bonds | ansible.utils.index_of('eq', bond) + 1}}"
    cmd:
      - nv set interface bond{{ bond_id }} bond member {{ bond }}
      - nv set interface bond{{ bond_id }} bond mlag id {{ bond_id }}
  with_items: "{{ bonds | split(',') }}"
  loop_control:
    loop_var: bonds_item

#
# Setting Peerlink ports for the mLag
#
- name: Peerlink ports for the mLag
  ansible.builtin.include_tasks: set_nv_commands.yml
  vars:
    swp_number: "{{ swp_item }}"
    cmd:
      - nv set interface peerlink bond member swp{{ swp_number }}
  with_sequence: start={{ mlag_peerlink_swp_start }} count=2
  loop_control:
    loop_var: swp_item
