---

- name: Checking if the configs exist
  become: true
  ansible.builtin.shell: |
    nv config show -o commands | grep '{{ cmd_to_check }}' | wc -l
  with_items: "{{ cmd }}"
  loop_control:
    loop_var: cmd_to_check
  register: cmd_exist
  vars:
    cmde: cmd
  changed_when: false

- name: Applying commands
  become: true
  ansible.builtin.shell: "{{ result_cmd.cmd_to_check }}"
  when: result_cmd.stdout != "1"
  with_items:
    - "{{ cmd_exist.results }}"
  loop_control:
    label: "Appying command : {{result_cmd.cmd_to_check}}"
    loop_var: result_cmd
  notify: SaveConfig

#- name: Debug
#  ansible.builtin.debug:
#    msg: "Msg: {{ item.item }} "
#  with_items:
#    - "{{ cmd_exist.results }}"
