---

#
# Setting BGP for the Leafs and Borders
#
- name: Setting BGP for Leafs and Borders
  ansible.builtin.include_tasks: set_nv_commands.yml
  vars:
    swp_range:
      "{{ '1-' + (number_of_ports | string) if
      (number_of_ports | int) > 1 else '1' }}"
    cmd:
      - nv set interface lo ip address {{ loopback }}/32
      - nv set interface swp{{ swp_range }} type swp
      - nv set router bgp autonomous-system {{ asn }}
      - nv set router bgp router-id {{ loopback }}
      - nv set vrf default router bgp timers keepalive 1
      - nv set vrf default router bgp timers hold 3
      - nv set vrf default router bgp timers connection-retry 3
      - nv set vrf default router bgp address-family ipv4-unicast network
        {{ loopback }}/32
      - nv set vrf default router bgp address-family ipv4-unicast redistribute
        connected
      - nv set evpn enable on

#
# Setting Leafs ports to the Spines
#
- name: Setting Leafs ports for Spines
  ansible.builtin.include_tasks: set_nv_commands.yml
  vars:
    swp_number: "{{ swp_item }}"
    cmd:
      - nv set vrf default router bgp neighbor swp{{ swp_number }}
        remote-as external
      - nv set vrf default router bgp neighbor swp{{ swp_number }}
        address-family l2vpn-evpn
        enable on
  with_sequence:
    start={{ spine_leaf_swp_start }} count={{ groups['spine'] | length }}
  loop_control:
    loop_var: swp_item
