---

#
# Setting the uplinks on the Leafs
#
- name: Setting uplinks for the Leafs
  ansible.builtin.include_tasks: set_nv_commands.yml
  vars:
    cmd:
      - nv set interface swp{{ swp_range_uplink }} bridge domain br_default
