---
#
# Setting the facts for all equipments
#

- name: Setting switchport list for the Spines to the Leafs
  set_fact:
    swp_list: "{{ swp_list | default([]) + [item | int]}}"
  with_sequence: start={{spine_leaf_swp_start}}
                 end={{spine_leaf_swp_start + groups['leaf'] | length - 1}}
  when: "'spine' in group_names"
  register: output

- name: Setting switchport list for the Spines to the Borders
  set_fact:
    swp_list: "{{ swp_list | default([]) + [item | int]}}"
  with_sequence: start={{spine_border_swp_start | int}}
                 end={{spine_border_swp_start | int + groups['border'] | length - 1}}
  when: "'spine' in group_names"
  register: output

- name: Simplifying switchport list
  vars:
    swp_list_sorted: "{{ swp_list | sort }}"
  set_fact:
    swp_range: "{{ lookup('ansible.builtin.template',
    'interface_to_list.j2') | replace('\n', '') }}"
  when: "'spine' in group_names"
  register: output

- name: Setting facts for Spine
  vars:
    node_id:
      "{{ groups['spine'] |
      ansible.utils.index_of('eq', inventory_hostname) + 1 }}"
  set_fact:
    hostname: 'SP-{{ site }}{{ "%02d" | format(node_id | int) }}'
    loopback: "{{ loopback_prefix }}.{{ site_id }}.{{ node_id }}"
    asn: '{{ asn_prefix }}{{ site_id }}{{ "%02d" | format(asn_spine_id) }}'
  when: "'spine' in group_names"

- name: Setting switchport list for the Leafs and Borders to Spines
  set_fact:
    swp_list: "{{ swp_list | default([]) + [item | int]}}"
  with_sequence: start={{spine_leaf_swp_start}}
                 end={{spine_leaf_swp_start + groups['spine'] | length - 1}}
  when: "'leaf' in group_names or 'border' in group_names"
  register: output

- name: Setting switchport list for the Leafs and Borders uplinks
  set_fact:
    swp_list: "{{ swp_list | default([]) + [item | int]}}"
    swp_list_uplinks: "{{ swp_list_uplinks | default([]) + [item | int]}}"
  with_items: "{{ uplinks }}"
  when: ("'leaf' in group_names or 'border' in group_names") and
        uplinks is defined
  register: output

- name: Setting switchport list for the Leafs mLag Bonds
  set_fact:
    swp_list: "{{ swp_list | default([]) + [item | int]}}"
  with_items: "{{ bonds }}"
  when: "'leaf' in group_names and bonds is defined"
  register: output

- name: Setting switchport list for the Leafs peerlink
  set_fact:
    swp_list: "{{ swp_list | default([]) + [item | int]}}"
  with_sequence: start={{mlag_peerlink_swp_start}}
                 end={{mlag_peerlink_swp_start | int + 1}}
  when: "'leaf' in group_names and bonds is defined"
  register: output

- name: Simplifying switchport list
  vars:
    swp_list_sorted: "{{ swp_list | sort }}"
  set_fact:
    swp_range: "{{ lookup('ansible.builtin.template',
    'interface_to_list.j2') | replace('\n', '') }}"
  when: "'leaf' in group_names or 'border' in group_names"
  register: output

- name: Simplifying switchport list for uplinks
  vars:
    swp_list_sorted: "{{ swp_list_uplinks | sort }}"
  set_fact:
    swp_range_uplink: "{{ lookup('ansible.builtin.template',
    'interface_to_list.j2') | replace('\n', '') }}"
  when: ("'leaf' in group_names or 'border' in group_names") and
        uplinks is defined
  register: output

- name: Setting facts for Leafs
  vars:
    node_id:
      "{{ groups['leaf'] |
      ansible.utils.index_of('eq', inventory_hostname) + 1 }}"
  set_fact:
    hostname: 'LF-{{ site }}{{ "%02d" | format(node_id | int) }}'
    loopback: "{{ loopback_prefix }}.{{ site_id }}.{{ (node_id | int) + 20 }}"
    asn:
      '{{ asn_prefix }}{{ site_id }}{{ "%02d" | format(node_id | int + 20) }}'
  when: "'leaf' in group_names"

- name: Setting facts for Borders
  vars:
    node_id:
      "{{ groups['border'] |
      ansible.utils.index_of('eq', inventory_hostname) + 1 }}"
  set_fact:
    hostname: 'BO-{{ site }}{{ "%02d" | format(node_id | int) }}'
    loopback: "{{ loopback_prefix }}.{{ site_id }}.{{ (node_id | int) + 50 }}"
    asn:
      '{{ asn_prefix }}{{ site_id }}{{ "%02d" | format(node_id | int + 50) }}'
  when: "'border' in group_names"

- name: Setting facts for mLag
  vars:
    node_id:
      "{{ groups['leaf'] |
      ansible.utils.index_of('eq', inventory_hostname) + 1 }}"
    mlag_pair_id:
      "{{ (node_id | int-1) if
              (node_id | int is divisibleby 2) else (node_id | int+1) }}"
    mlag_shared_id:
      "{{ (node_id | int-1) if (node_id | int is divisibleby 2) else node_id }}"
  set_fact:
    mlag_mac: '{{ mlag_mac_prefix }}:{{ "%02d" | format(site_id) }}:{{ "%02d" |
      format(mlag_shared_id | int) }}'
    mlag_ip_backup:
      '{{ loopback_prefix }}.{{ site_id }}.{{ (mlag_pair_id | int) + 20 }}'
    mlag_shared_ip:
      '{{ mlag_prefix }}.{{ site_id }}.{{ (mlag_shared_id | int) + 20 }}'
  when:
    "'leaf' in group_names and (bonds is defined)"
