---
- name: Testing
  hosts: cumulus
  gather_facts: false

  handlers:
    - name: SaveConfig
      become: true
      ansible.builtin.command:
        nv config apply -y

  tasks:
    - name: Applying command
      become: true
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - nv unset system
        - nv unset service
        - nv unset router
        - nv unset vrf
        - nv unset evpn
        - nv unset nve
        - nv unset interface lo
        - nv unset interface swp1-6
        - nv unset bridge
        - nv unset interface vlan1-4094
        - nv unset interface bond1
        - nv unset interface bond2
        - nv unset mlag
        - nv unset interface peerlink
        - nv unset interface peerlink.4094
      notify: SaveConfig
