---
- name: Restoring config on all cumulus switches
  hosts: cumulus

  handlers:
    - name: SaveConfig
      become: true
      ansible.builtin.command:
        nv config apply -y

  tasks:
    - name: Applying command
      become: true
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - nv unset system hostname
        - nv unset service ntp
        - nv unset router bgp
        - nv unset interface lo ip address
      notify: SaveConfig
