---
- name: Testing
  hosts: cumulus
  gather_facts: false

  tasks:
    - name: Showing configuration as commands
      become: true
      ansible.builtin.shell: net show route
      register: output
      changed_when: false
    - name:
      ansible.builtin.debug:
        var: output.stdout_lines
