---
- name: Testing
  hosts: cumulus
  gather_facts: false

  tasks:
    - name: Settings bonds
      ansible.builtin.debug:
        msg:
          - "{{ groups['leaf'] | ansible.utils.index_of('eq', inventory_hostname) + 1 }}"


#- name: Settings bonds
#  ansible.builtin.include_tasks: set_nv_commands.yml
#  vars:
#    bond: "{{ bonds_item }}"
#    bond_id: "{{ bonds | ansible.utils.index_of('eq', bond, wantlist=True) | int + 1}}"
#    cmd:
#      - nv set interface bond{{ bond_id }} bond member {{ bond }}
#      - nv set interface bond{{ bond_id }} bond mlag id {{ bond_id }}
#  with_items: "{{ bonds | split(',') }}"
#  loop_control:
#    loop_var: bonds_item
