---
- name: Testing
  hosts: all
  gather_facts: true

  tasks:
    - name: Building result
      set_fact:
        swp_list: "{{ ansible_facts['interfaces'] | select('match', 'swp*') }}"
      register: output

    - name: Debug
      ansible.builtin.debug:
        var: output
