---

- name: "{{test_name}}"
  ansible.builtin.include_tasks: simplify_list.yml
  register: simplified_list

- name: Validating "{{test_name}}"
  ignore_errors: true
  fail:
    msg:
      - "{{test_name}}"
      - "Result do not match :"
      - "Expected : {{ expected_result }}"
      - "Result : {{ output_list }}"
  when: (expected_result) != (output_list)
